services:
  web-app:
    build:
      context: './web-app/docker'
      dockerfile: Dockerfile
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    ports:
      - '80:80'
      - '5173:5173'
    volumes:
      - './web-app:/var/www/html'
    networks:
      - uptime-monitor
    depends_on:
      - pgsql.web-app
      - kafka
      - redis.web-app
  monitor-management:
    build:
      context: './monitor-management/docker'
      dockerfile: Dockerfile
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    volumes:
      - './monitor-management:/var/www/html'
    networks:
      - uptime-monitor
    depends_on:
      - pgsql.monitor-management
      - kafka
      - redis.monitor-management
  pgsql.web-app:
    image: postgres:13-alpine3.22
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: user
      POSTGRES_DB: db
    ports:
      - '5432:5432'
    networks:
      - uptime-monitor
  pgsql.monitor-management:
    image: postgres:13-alpine3.22
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: user
      POSTGRES_DB: db
      PGPORT: 5433
    ports:
      - '5433:5433'
    networks:
      - uptime-monitor
  redis.web-app:
    image: redis:7.4.4-alpine3.21
    command: ["redis-server", "--requirepass", "root"]
    ports:
      - '6379:6379'
    networks:
      - uptime-monitor
  redis.monitor-management:
    image: redis:7.4.4-alpine3.21
    command: [ "redis-server", "--requirepass", "root", "--port", "6380"]
    ports:
      - '6380:6380'
    networks:
      - uptime-monitor
  kafdrop:
    image: obsidiandynamics/kafdrop:4.1.0
    environment:
      - KAFKA_BROKERCONNECT=kafka:9092
    ports:
      - '9000:9000'
    networks:
      - uptime-monitor
    depends_on:
      - kafka
  kafka:
    image: bitnami/kafka:4.0.0
    environment:
      - KAFKA_CFG_NODE_ID=0
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@kafka:9093
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
    networks:
      - uptime-monitor

networks:
  uptime-monitor:
    driver: bridge