[supervisord]
nodaemon=true
user=1000
directory=/var/www/html
logfile=/var/www/html/storage/logs/supervisord.log
pidfile=/var/www/html/storage/logs/supervisord.pid

[program:laravel-worker]
command=php artisan queue:work --queue=default --sleep=3 --tries=3 --max-time=3600
process_name=%(program_name)s_%(process_num)02d
numprocs=8
autostart=true
autorestart=true
stopasgroup=true
killasgroup=true
stderr_logfile=/var/www/html/storage/logs/laravel-worker.err.log
stdout_logfile=/var/www/html/storage/logs/laravel-worker.out.log
