[supervisord]
nodaemon=true
user=1000
directory=/var/www/html
logfile=/var/www/html/storage/logs/supervisord.log
pidfile=/var/www/html/storage/logs/supervisord.pid

[program:php]
command=php -d variables_order=EGPCS artisan serve --host=0.0.0.0 --port=80
autostart=true
autorestart=true
stderr_logfile=/var/www/html/storage/logs/php.err.log
stdout_logfile=/var/www/html/storage/logs/php.out.log

[program:vite]
command=npm run dev
autostart=true
autorestart=true
stderr_logfile=/var/www/html/storage/logs/vite.err.log
stdout_logfile=/var/www/html/storage/logs/vite.out.log
