[supervisord]
nodaemon=true
user=root
logfile=/var/log/supervisord.log
pidfile=/var/run/supervisord.pid

[program:laravel-worker]
command=/usr/local/bin/php /var/www/html/artisan queue:work --queue=default --sleep=3 --tries=3 --max-time=3600
process_name=%(program_name)s_%(process_num)02d
numprocs=8
autostart=true
autorestart=true
stopasgroup=true
killasgroup=true
stderr_logfile=/var/log/laravel-worker.err.log
stdout_logfile=/var/log/laravel-worker.out.log

[program:consumer-monitor.create]
command=/usr/local/bin/php /var/www/html/artisan kafka:consume --consumer=App\\Kafka\\Consumers\\MonitorCreateConsumer --topics=monitor_management.monitor.create
autostart=true
autorestart=true
stdout_logfile=/var/log/consumer-monitor.create.log
stderr_logfile=/var/log/consumer-monitor.create.err.log

[program:consumer-ping.check.reply]
command=/usr/local/bin/php /var/www/html/artisan kafka:consume --consumer=App\\Kafka\\Consumers\\PingCheckReplyConsumer --topics=checker.ping.check.reply
autostart=true
autorestart=true
stdout_logfile=/var/log/consumer-ping.check.reply.log
stderr_logfile=/var/log/consumer-ping.check.reply.err.log
